// SPDX-License-Identifier: Apache-2.0
// Copyright Authors of Kerria

package scaffold

import (
	yaml "sigs.k8s.io/yaml/goyaml.v3"
)

func ScaffoldKustomization() *yaml.Node {
	return document(
		comment("Resource generated by Kerria. DO NOT EDIT", mapping(
			[][]*yaml.Node{
				mapPair("apiVersion", "kustomize.config.k8s.io/v1beta1"),
				mapPair("kind", "Kustomization"),
				mapKey("resources", sequence(
					[]*yaml.Node{
						scalar("build.yaml"),
					},
				)),
			},
		)))
}
